# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

   trigger:
     branches:
       include:
       - main
       - develop
       - Pipeline-Testing

   pool:
     vmImage: 'ubuntu-latest'

   steps:
   - checkout: self
     fetchDepth: 0

   - script: |
       git remote set-url azure https://PAT:$(AZURE_PAT)@dev.azure.com/JeppeMarek/_git/Valgfagsportfolio 2>/dev/null || git remote add azure https://PAT:$(AZURE_PAT)@dev.azure.com/JeppeMarek/_git/Valgfagsportfolio
       git push azure --all
       git push azure --tags
     displayName: 'Push to Azure Repos'
     env:
       AZURE_PAT: $(AZURE_PAT)
